const data = {
  products: [
    {
      name: "Bamboo Toothbrush",
      slug: "bamboo-toothbrush",
      category: "Bamboo",
      image: "/./images/bamboo-toothbrush.webp",
      price: 70,
      brand: "Kirtan Bamboo's",
      rating: 4.5,
      nuMReviews: 10,
      countInStock: 6,
      description: "Eco-Friendly Bamboo Toothbrush",
    },
    {
      name: "Paper Bag",
      slug: "paper-bag",
      category: "Paper",
      image: "/./images/paper-bag.jpg",
      price: 10,
      brand: "Golden Bags",
      rating: 3.9,
      nuMReviews: 10,
      countInStock: 6,
      description: "Eco-Friendly Bamboo Toothbrush",
    },
    {
      name: "Bamboo Toothbrush",
      slug: "bamboo-toothbr",
      category: "Bamboo",
      image: "/./images/bamboo-toothbrush.webp",
      price: 70,
      brand: "Kirtan Bamboo's",
      rating: 4.5,
      nuMReviews: 10,
      countInStock: 6,
      description: "Eco-Friendly Bamboo Toothbrush",
    },
    {
      name: "Bamboo Toothbrush",
      slug: "bamboo-toothbr",
      category: "Bamboo",
      image: "/./images/paper-bag.jpg",
      price: 70,
      brand: "Kirtan Bamboo's",
      rating: 4.5,
      nuMReviews: 10,
      countInStock: 6,
      description: "Eco-Friendly Bamboo Toothbrush",
    },
  ],
};

export default data;
